// <auto-generated />
using System;
using IotDashboardApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IotDashboardApplication.Migrations
{
    [DbContext(typeof(IotContext))]
    [Migration("20250812113906_InitData")]
    partial class InitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IotDashboardApplication.Entities.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Datas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 8, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.0,
                            Temperature = 22.0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 8, 12, 11, 1, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.100000000000001,
                            Temperature = 22.100000000000001
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 8, 12, 11, 2, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.200000000000003,
                            Temperature = 22.199999999999999
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 8, 12, 11, 3, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.299999999999997,
                            Temperature = 22.300000000000001
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 8, 12, 11, 4, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.399999999999999,
                            Temperature = 22.399999999999999
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 8, 12, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.5,
                            Temperature = 22.5
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 8, 12, 11, 6, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.600000000000001,
                            Temperature = 22.600000000000001
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 8, 12, 11, 7, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.700000000000003,
                            Temperature = 22.699999999999999
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 8, 12, 11, 8, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.799999999999997,
                            Temperature = 22.800000000000001
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 8, 12, 11, 9, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 50.899999999999999,
                            Temperature = 22.899999999999999
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 8, 12, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.0,
                            Temperature = 23.0
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 8, 12, 11, 11, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.100000000000001,
                            Temperature = 23.100000000000001
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 8, 12, 11, 12, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.200000000000003,
                            Temperature = 23.199999999999999
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 8, 12, 11, 13, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.299999999999997,
                            Temperature = 23.300000000000001
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 8, 12, 11, 14, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.399999999999999,
                            Temperature = 23.399999999999999
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 8, 12, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.5,
                            Temperature = 23.5
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 8, 12, 11, 16, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.600000000000001,
                            Temperature = 23.600000000000001
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2025, 8, 12, 11, 17, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.700000000000003,
                            Temperature = 23.699999999999999
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 8, 12, 11, 18, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.799999999999997,
                            Temperature = 23.800000000000001
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2025, 8, 12, 11, 19, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 51.899999999999999,
                            Temperature = 23.899999999999999
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2025, 8, 12, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.0,
                            Temperature = 24.0
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2025, 8, 12, 11, 21, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.100000000000001,
                            Temperature = 24.100000000000001
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2025, 8, 12, 11, 22, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.200000000000003,
                            Temperature = 24.199999999999999
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2025, 8, 12, 11, 23, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.299999999999997,
                            Temperature = 24.300000000000001
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2025, 8, 12, 11, 24, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.399999999999999,
                            Temperature = 24.399999999999999
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2025, 8, 12, 11, 25, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.5,
                            Temperature = 24.5
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2025, 8, 12, 11, 26, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.600000000000001,
                            Temperature = 24.600000000000001
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2025, 8, 12, 11, 27, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.700000000000003,
                            Temperature = 24.699999999999999
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2025, 8, 12, 11, 28, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.799999999999997,
                            Temperature = 24.800000000000001
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2025, 8, 12, 11, 29, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 52.899999999999999,
                            Temperature = 24.899999999999999
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2025, 8, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.0,
                            Temperature = 25.0
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2025, 8, 12, 11, 31, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.100000000000001,
                            Temperature = 25.100000000000001
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2025, 8, 12, 11, 32, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.200000000000003,
                            Temperature = 25.199999999999999
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2025, 8, 12, 11, 33, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.299999999999997,
                            Temperature = 25.300000000000001
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2025, 8, 12, 11, 34, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.399999999999999,
                            Temperature = 25.399999999999999
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2025, 8, 12, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.5,
                            Temperature = 25.5
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2025, 8, 12, 11, 36, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.600000000000001,
                            Temperature = 25.600000000000001
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2025, 8, 12, 11, 37, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.700000000000003,
                            Temperature = 25.699999999999999
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2025, 8, 12, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.799999999999997,
                            Temperature = 25.800000000000001
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2025, 8, 12, 11, 39, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 53.899999999999999,
                            Temperature = 25.899999999999999
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2025, 8, 12, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.0,
                            Temperature = 26.0
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2025, 8, 12, 11, 41, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.100000000000001,
                            Temperature = 26.100000000000001
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2025, 8, 12, 11, 42, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.200000000000003,
                            Temperature = 26.199999999999999
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2025, 8, 12, 11, 43, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.299999999999997,
                            Temperature = 26.300000000000001
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2025, 8, 12, 11, 44, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.399999999999999,
                            Temperature = 26.399999999999999
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2025, 8, 12, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.5,
                            Temperature = 26.5
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2025, 8, 12, 11, 46, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.600000000000001,
                            Temperature = 26.600000000000001
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2025, 8, 12, 11, 47, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.700000000000003,
                            Temperature = 26.699999999999999
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2025, 8, 12, 11, 48, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.799999999999997,
                            Temperature = 26.800000000000001
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2025, 8, 12, 11, 49, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 54.899999999999999,
                            Temperature = 26.899999999999999
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2025, 8, 12, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.0,
                            Temperature = 27.0
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2025, 8, 12, 11, 51, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.100000000000001,
                            Temperature = 27.100000000000001
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2025, 8, 12, 11, 52, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.200000000000003,
                            Temperature = 27.199999999999999
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2025, 8, 12, 11, 53, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.299999999999997,
                            Temperature = 27.300000000000001
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2025, 8, 12, 11, 54, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.399999999999999,
                            Temperature = 27.399999999999999
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2025, 8, 12, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.5,
                            Temperature = 27.5
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2025, 8, 12, 11, 56, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.600000000000001,
                            Temperature = 27.600000000000001
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2025, 8, 12, 11, 57, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.700000000000003,
                            Temperature = 27.699999999999999
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2025, 8, 12, 11, 58, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.799999999999997,
                            Temperature = 27.800000000000001
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2025, 8, 12, 11, 59, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 55.899999999999999,
                            Temperature = 27.899999999999999
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2025, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.0,
                            Temperature = 28.0
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2025, 8, 12, 12, 1, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.100000000000001,
                            Temperature = 28.100000000000001
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2025, 8, 12, 12, 2, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.200000000000003,
                            Temperature = 28.199999999999999
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2025, 8, 12, 12, 3, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.299999999999997,
                            Temperature = 28.300000000000001
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2025, 8, 12, 12, 4, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.399999999999999,
                            Temperature = 28.399999999999999
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2025, 8, 12, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.5,
                            Temperature = 28.5
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2025, 8, 12, 12, 6, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.600000000000001,
                            Temperature = 28.600000000000001
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2025, 8, 12, 12, 7, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.700000000000003,
                            Temperature = 28.699999999999999
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2025, 8, 12, 12, 8, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.799999999999997,
                            Temperature = 28.800000000000001
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2025, 8, 12, 12, 9, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 56.899999999999999,
                            Temperature = 28.899999999999999
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2025, 8, 12, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.0,
                            Temperature = 29.0
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2025, 8, 12, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.100000000000001,
                            Temperature = 29.100000000000001
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2025, 8, 12, 12, 12, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.200000000000003,
                            Temperature = 29.199999999999999
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2025, 8, 12, 12, 13, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.299999999999997,
                            Temperature = 29.300000000000001
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2025, 8, 12, 12, 14, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.399999999999999,
                            Temperature = 29.399999999999999
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2025, 8, 12, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.5,
                            Temperature = 29.5
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2025, 8, 12, 12, 16, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.600000000000001,
                            Temperature = 29.600000000000001
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2025, 8, 12, 12, 17, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.700000000000003,
                            Temperature = 29.699999999999999
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2025, 8, 12, 12, 18, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.799999999999997,
                            Temperature = 29.800000000000001
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2025, 8, 12, 12, 19, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 57.899999999999999,
                            Temperature = 29.899999999999999
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2025, 8, 12, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.0,
                            Temperature = 30.0
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2025, 8, 12, 12, 21, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.100000000000001,
                            Temperature = 30.100000000000001
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2025, 8, 12, 12, 22, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.200000000000003,
                            Temperature = 30.200000000000003
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2025, 8, 12, 12, 23, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.299999999999997,
                            Temperature = 30.300000000000001
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2025, 8, 12, 12, 24, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.399999999999999,
                            Temperature = 30.399999999999999
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2025, 8, 12, 12, 25, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.5,
                            Temperature = 30.5
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2025, 8, 12, 12, 26, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.600000000000001,
                            Temperature = 30.600000000000001
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2025, 8, 12, 12, 27, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.700000000000003,
                            Temperature = 30.700000000000003
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2025, 8, 12, 12, 28, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.799999999999997,
                            Temperature = 30.800000000000001
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2025, 8, 12, 12, 29, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 58.899999999999999,
                            Temperature = 30.899999999999999
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2025, 8, 12, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.0,
                            Temperature = 31.0
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2025, 8, 12, 12, 31, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.100000000000001,
                            Temperature = 31.100000000000001
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2025, 8, 12, 12, 32, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.200000000000003,
                            Temperature = 31.200000000000003
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTime(2025, 8, 12, 12, 33, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.299999999999997,
                            Temperature = 31.300000000000001
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTime(2025, 8, 12, 12, 34, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.399999999999999,
                            Temperature = 31.399999999999999
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTime(2025, 8, 12, 12, 35, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.5,
                            Temperature = 31.5
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTime(2025, 8, 12, 12, 36, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.600000000000001,
                            Temperature = 31.600000000000001
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTime(2025, 8, 12, 12, 37, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.700000000000003,
                            Temperature = 31.700000000000003
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTime(2025, 8, 12, 12, 38, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.799999999999997,
                            Temperature = 31.800000000000001
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTime(2025, 8, 12, 12, 39, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 59.899999999999999,
                            Temperature = 31.899999999999999
                        });
                });

            modelBuilder.Entity("IotDashboardApplication.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
